inventory.addBackpack =#add-to-cart-sauce-labs-backpack
inventory.removeBack =#remove-sauce-labs-backpack
inventory.addBikeLight =#add-to-cart-sauce-labs-bike-light
inventory.removeBikeLight =#remove-sauce-labs-bike-light
